version: '3'

services:
  toolkit:
    image: ghcr.io/mrsupiri/toolkit:latest
    ports:
      - "3000:3000"
    volumes:
      - ./service_accounts:/usr/src/app/service_accounts
      - .env:/usr/src/app/.env
      - ./db:/usr/src/app/db
    depends_on:
      - selenium
    restart: always
  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: '2g'
    restart: always
    environment:
      - SE_NODE_SESSION_TIMEOUT=2147483646
