name: PR Check

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/mrsupiri/toolkit
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Setup sqlx
        run: |
          cargo install sqlx-cli
          sqlx db setup --database-url=sqlite:toolkit.db
      - name: Build and test
        run: |
          export DATABASE_URL=sqlite:toolkit.db
          cargo build --verbose
          cargo test --verbose
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t $IMAGE_NAME:latest .
